### ISSUE TITLE
Failed Generate preview html

### ISSUE THREAD

**Issue by tsuyoshicho** [iwataka/minidown.vim#1]
Path with space (ex /test case/test.md) are failed preview.

---

パスに空白を含むとプレビューに失敗します。htmlファイルが生成されていないように見えるのでそこで失敗しているのではないかと。
たぶん、pandocへ与えるファイル名が""で括られていればいいのではないかと思われますが...
 *nix環境 でも空白はけっこうありえると思いますので、一般的な対応方法がある気がします

Win7 パッチ最新
Vim 8.0.604
minidown.vim HEAD

**Comment by iwataka** [comment]
65a364fd09f5adf0eae4b6e5fac7f2ca06f12bd9
474bc08a06d1ebd905300bb825baaff350cc1ee1
修正したのでクローズします。

**Comment by tsuyoshicho** [comment]
ありがとうございます。
